# Generated by Django 5.2.6 on 2025-10-04 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='domicilior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=70)),
                ('region', models.CharField(choices=[('RN', 'Region Norte'), ('RAN', 'Region Altos Norte'), ('RAS', 'Region Altos Sur'), ('RC', 'Region Cienega'), ('RSE', 'Region Sureste'), ('RS', 'Region Sur'), ('RSA', 'Region Sierra de Amula'), ('RCS', 'Region Costa Sur'), ('RCN', 'Region Costa Norte'), ('RSO', 'Region Sierra Occidental'), ('RV', 'Region Valles'), ('RCC', 'Region Centro')], max_length=3)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
