# Generated by Django 5.2.6 on 2025-10-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilior',
            name='municipio',
            field=models.CharField(choices=[('ACA', 'Acatic'), ('ACJ', 'Acatlán de Juárez'), ('ADM', 'Ahualulco de Mercado'), ('AMA', 'Amacueca'), ('AMT', 'Amatitán'), ('AM', 'Ameca'), ('AR', 'Arandas'), ('ATM', 'Atemajac de Brizuela'), ('AT', 'Atengo'), ('ATE', 'Atenguillo'), ('ATO', 'Atotonilco el Alto'), ('ATY', 'Atoyac'), ('AUN', 'Autlán de Navarro'), ('AYT', 'Ayotlán'), ('AYL', 'Ayutla'), ('BO', 'Bolaños'), ('CC', 'Cabo Corrientes'), ('CO', 'Cocula'), ('CCA', 'Casimiro Castillo'), ('CH', 'Chapala'), ('CHI', 'Chimaltitán'), ('CHQ', 'Chiquilistlán'), ('CIH', 'Cihuatlán'), ('COL', 'Colotlán'), ('CBA', 'Concepción de Buenos Aires'), ('CGB', 'Cuautitlán de García Barragán'), ('CU', 'Cuautla'), ('CUQ', 'Cuquío'), ('DE', 'Degollado'), ('EH', 'Ejutla'), ('EA', 'El Arenal'), ('EG', 'El Grullo'), ('EL', 'El Limón'), ('ES', 'El Salto'), ('ED', 'Encarnación de Díaz'), ('ET', 'Etzatlán'), ('GF', 'Gómez Farías'), ('GU', 'Guachinango'), ('GUA', 'Guadalajara'), ('HOT', 'Hostotipaquillo'), ('HJ', 'Huejúcar'), ('HA', 'Huejuquilla el Alto'), ('IM', 'Ixtlahuacán de los Membrillos'), ('IR', 'Ixtlahuacán del Río'), ('JAL', 'Jalostotitlán'), ('JAM', 'Jamay'), ('JM', 'Jesús María'), ('JD', 'Jilotlán de los Dolores'), ('JTC', 'Jocotepec'), ('JU', 'Juanacatlán'), ('JUC', 'Juchitlán'), ('LB', 'La Barca'), ('LH', 'La Huerta'), ('LMP', 'La Manzanilla de la Paz'), ('LM', 'Lagos de Moreno'), ('MAG', 'Magdalena'), ('MAS', 'Mascota'), ('MAZ', 'Mazamitla'), ('MEX', 'Mexticacán'), ('MEZ', 'Mezquitic'), ('MIX', 'Mixtlán'), ('OCO', 'Ocotlán'), ('OJ', 'Ojuelos de Jalisco'), ('PI', 'Pihuamo'), ('PON', 'Poncitlán'), ('PTV', 'Puerto Vallarta'), ('QUI', 'Quitupan'), ('SCB', 'San Cristóbal de la Barranca'), ('SDA', 'San Diego de Alejandría'), ('SG', 'San Gabriel'), ('SICG', 'San Ignacio Cerro Gordo'), ('SJL', 'San Juan de los Lagos'), ('SJE', 'San Juanito de Escobedo'), ('SJ', 'San Julián'), ('SM', 'San Marcos'), ('SMB', 'San Martín de Bolaños'), ('SMH', 'San Martín Hidalgo'), ('SMA', 'San Miguel el Alto'), ('SPT', 'San Pedro Tlaquepaque'), ('SBO', 'San Sebastián del Oeste'), ('SMAA', 'Santa María de los Angeles'), ('SMO', 'Santa María del Oro'), ('SAY', 'Sayula'), ('TAL', 'Tala'), ('TLA', 'Talpa de Allende'), ('TG', 'Tamazula de Gordiano'), ('TAP', 'Tapalpa'), ('TEC', 'Tecalitlán'), ('TM', 'Techaluta de Montenegro'), ('TEO', 'Tecolotlán'), ('TEN', 'Tenamaxtlán'), ('TOA', 'Teocaltiche'), ('TOC', 'Teocuitatlán de Corona'), ('TEM', 'Tepatitlán de Morelos'), ('TQ', 'Tequila'), ('TCH', 'Teuchitlán'), ('TIA', 'Tizapán el Alto'), ('TLZ', 'Tlajomulco de Zuñiga'), ('TOLI', 'Tolimán'), ('TMT', 'Tomatlán'), ('TONA', 'Tonalá'), ('TONY', 'Tonaya'), ('TONI', 'Tonila'), ('TOTA', 'Totatiche'), ('TOTO', 'Tototlán'), ('TUX', 'Tuxcacuesco'), ('TUXC', 'Tuxcueca'), ('TUXP', 'Tuxpan'), ('USAA', 'Unión de San Antonio'), ('UT', 'Unión de Tula'), ('VG', 'Valle de Guadalupe'), ('VJ', 'Valle de Juárez'), ('VC', 'Villa Corona'), ('VIG', 'Villa Guerrero'), ('VH', 'Villa Hidalgo'), ('CP', 'Villa Purificación'), ('YA', 'Yahualica de González Gallo'), ('ZAT', 'Zapotiltic'), ('ZAP', 'Zapopan'), ('ZAV', 'Zapotitlán de Vadillo'), ('ZAR', 'Zapotlán del Rey'), ('ZAG', 'Zapotlán el Grande'), ('ZAPT', 'Zapotlanejo')], max_length=5),
        ),
    ]
