# Generated by Django 5.2.6 on 2025-10-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_consumoagua_recomendaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(upload_to='carrusel/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveBigIntegerField(default=0, help_text='Orden del carrusel')),
                ('activo', models.BooleanField(default=True, help_text='Mostrar en carrusel')),
            ],
            options={
                'verbose_name': 'Foto de carrusel',
                'verbose_name_plural': 'Fotos del carrusel',
                'ordering': ['orden'],
            },
        ),
    ]
