# Generated by Django 5.2.6 on 2025-10-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0004_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumoagua',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
