# Generated by Django 5.2.6 on 2025-10-18 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0007_alter_consumoagua_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumoagua',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
