# Generated by Django 5.2.6 on 2025-10-19 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0008_alter_consumoagua_cantidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegresionMetricas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrenamiento', models.DateTimeField(auto_now_add=True)),
                ('r2', models.FloatField()),
                ('mse', models.FloatField()),
                ('b0', models.FloatField()),
                ('b1', models.FloatField()),
                ('prediccion', models.FloatField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
