# Generated by Django 5.2.6 on 2025-10-25 21:16

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0012_kmeansresultado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendaciones',
            name='algoritmo',
            field=models.CharField(choices=[('regresion', 'Regresión'), ('bayes', 'Naive Bayes'), ('kmeans', 'K-Means'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='recomendaciones',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='recomendaciones',
            constraint=models.UniqueConstraint(fields=('id_usuario', 'algoritmo', 'fecha'), name='uniq_rec_usuario_algoritmo_fecha'),
        ),
    ]
