# Generated by Django 5.2.6 on 2025-11-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0013_recomendaciones_algoritmo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilior',
            name='miembros_domicilio',
            field=models.PositiveIntegerField(blank=True, help_text='Número de personas que viven en el domicilio', null=True),
        ),
    ]
