# Generated by Django 5.2.6 on 2025-11-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0014_domicilior_miembros_domicilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumoagua',
            name='tipo_consumo',
            field=models.CharField(blank=True, choices=[('DOMESTICO', 'Doméstico'), ('GANADERO', 'Ganadero'), ('AGRICOLA', 'Agrícola'), ('INDUSTRIAL', 'Industrial'), ('COMERCIAL_SERVICIOS', 'Comercial / Servicios'), ('PUBLICO_URBANO', 'Público / Urbano'), ('RECREATIVO', 'Recreativo'), ('OTRO', 'Otro')], help_text='Tipo general de consumo de agua', max_length=30, null=True),
        ),
    ]
